version: '3.8'

services:
  web:
    environment:
      - DJANGO_DEBUG=${DJANGO_DEBUG:-True}
    volumes:
      - ./api:/app
  frontend:
    build:
      args:
        - VITE_API_URL=${VITE_API_URL:-http://localhost:5000/graphql}
    ports:
      - "3000:80"
