# Generated by Django 5.0.2 on 2025-07-25 17:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DownloadHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.CharField(max_length=2048)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(default=None, null=True)),
                (
                    "progress",
                    models.SmallIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(1000),
                        ],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TrackedPlaylist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=2048)),
                ("url", models.CharField(max_length=2048, unique=True)),
                ("enabled", models.BooleanField(default=True)),
                ("auto_track_artists", models.BooleanField(default=False)),
                ("last_synced_at", models.DateTimeField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("gid", models.CharField(max_length=120, unique=True)),
                ("tracked", models.BooleanField(default=False)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                ("last_synced_at", models.DateTimeField(default=None, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["gid"], name="library_man_gid_46cefb_idx"),
                    models.Index(
                        fields=["tracked"], name="library_man_tracked_5fa14f_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("spotify_gid", models.CharField(max_length=2048, unique=True)),
                ("spotify_uri", models.CharField(max_length=2048)),
                ("downloaded", models.BooleanField(default=False)),
                ("total_tracks", models.IntegerField(default=0)),
                ("wanted", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=2048)),
                ("failed_count", models.IntegerField(default=0)),
                ("album_type", models.CharField(max_length=100, null=True)),
                ("album_group", models.CharField(max_length=100, null=True)),
                (
                    "artist",
                    models.ForeignKey(
                        db_column="artist_gid",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="library_manager.artist",
                        to_field="gid",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("gid", models.CharField(max_length=120, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("failed_count", models.IntegerField(default=0)),
                ("bitrate", models.IntegerField(default=0)),
                ("unavailable", models.BooleanField(default=False)),
                ("file_path", models.FilePathField(null=True)),
                ("downloaded", models.BooleanField(default=False)),
                (
                    "primary_artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="library_manager.artist",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContributingArtist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="library_manager.artist",
                    ),
                ),
                (
                    "song",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="library_manager.song",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="song",
            index=models.Index(fields=["gid"], name="library_man_gid_2ef37b_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="contributingartist",
            unique_together={("song", "artist")},
        ),
    ]
