# Generated by Django 5.0.2 on 2025-07-28 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("library_manager", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_id", models.CharField(max_length=255, unique=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("SYNC", "Sync"),
                            ("DOWNLOAD", "Download"),
                            ("FETCH", "Fetch"),
                        ],
                        max_length=20,
                    ),
                ),
                ("entity_id", models.CharField(max_length=255)),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("ARTIST", "Artist"),
                            ("ALBUM", "Album"),
                            ("PLAYLIST", "Playlist"),
                            ("TRACK", "Track"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("duration_seconds", models.IntegerField(blank=True, null=True)),
                ("progress_percentage", models.FloatField(default=0.0)),
                ("log_messages", models.JSONField(blank=True, default=list)),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
    ]
