# Generated by Django 5.0.2 on 2025-07-28 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("library_manager", "0002_taskhistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskhistory",
            name="last_heartbeat",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="taskhistory",
            name="timeout_minutes",
            field=models.IntegerField(default=30),
        ),
    ]
