# Generated by Django 5.0.2 on 2025-07-28 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("library_manager", "0003_taskhistory_last_heartbeat_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskhistory",
            name="last_heartbeat",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
