# Generated by Django 5.0.2 on 2025-07-29 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("library_manager", "0004_alter_taskhistory_last_heartbeat"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="taskhistory",
            index=models.Index(
                fields=["status", "-started_at"], name="library_man_status_dfb074_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taskhistory",
            index=models.Index(
                fields=["type", "-started_at"], name="library_man_type_f81fd9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taskhistory",
            index=models.Index(
                fields=["entity_type", "-started_at"],
                name="library_man_entity__2522da_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="taskhistory",
            index=models.Index(
                fields=["completed_at"], name="library_man_complet_362457_idx"
            ),
        ),
    ]
