# Generated by Django 5.0.2 on 2025-09-11 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("library_manager", "0007_filepath_deduplication"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artist",
            name="name",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="song",
            name="name",
            field=models.CharField(max_length=500),
        ),
    ]
