# Generated by Django 5.0.2 on 2025-09-11 18:06

from django.db import migrations


def increase_name_field_lengths(apps, schema_editor):
    """Increase name field lengths if tables exist."""
    from django.db import connection

    with connection.cursor() as cursor:
        # Check if tables exist and alter them if they do
        cursor.execute(
            """
            SELECT EXISTS (
                SELECT FROM information_schema.tables
                WHERE table_schema = 'public' AND table_name = 'artists'
            );
        """
        )
        if cursor.fetchone()[0]:
            cursor.execute("ALTER TABLE artists ALTER COLUMN name TYPE VARCHAR(500);")

        cursor.execute(
            """
            SELECT EXISTS (
                SELECT FROM information_schema.tables
                WHERE table_schema = 'public' AND table_name = 'songs'
            );
        """
        )
        if cursor.fetchone()[0]:
            cursor.execute("ALTER TABLE songs ALTER COLUMN name TYPE VARCHAR(500);")


def reverse_name_field_lengths(apps, schema_editor):
    """Reverse the name field length changes."""
    from django.db import connection

    with connection.cursor() as cursor:
        # Check if tables exist and alter them if they do
        cursor.execute(
            """
            SELECT EXISTS (
                SELECT FROM information_schema.tables
                WHERE table_schema = 'public' AND table_name = 'artists'
            );
        """
        )
        if cursor.fetchone()[0]:
            cursor.execute("ALTER TABLE artists ALTER COLUMN name TYPE VARCHAR(200);")

        cursor.execute(
            """
            SELECT EXISTS (
                SELECT FROM information_schema.tables
                WHERE table_schema = 'public' AND table_name = 'songs'
            );
        """
        )
        if cursor.fetchone()[0]:
            cursor.execute("ALTER TABLE songs ALTER COLUMN name TYPE VARCHAR(200);")


class Migration(migrations.Migration):

    dependencies = [
        ("library_manager", "0007_filepath_deduplication"),
    ]

    operations = [
        migrations.RunPython(
            increase_name_field_lengths,
            reverse_name_field_lengths,
        ),
    ]
