# Generated by Django 5.2.5 on 2025-09-24 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("library_manager", "0009_state_reconciliation"),
    ]

    operations = [
        # Add check constraint to prevent null task names in TaskResult
        migrations.RunSQL(
            sql="""
            ALTER TABLE django_celery_results_taskresult
            ADD CONSTRAINT task_name_not_null_or_empty
            CHECK (task_name IS NOT NULL AND task_name != '');
            """,
            reverse_sql="""
            ALTER TABLE django_celery_results_taskresult
            DROP CONSTRAINT IF EXISTS task_name_not_null_or_empty;
            """,
        ),
    ]
