# Generated by Django 5.2.6 on 2025-11-14 18:34

from django.db import migrations


def fix_crontab_schedules(apps, schema_editor):
    """
    Fix crontab schedules that were stored with invalid curly brace syntax.

    Celery beat's DatabaseScheduler only recognizes standard cron syntax like
    "*/5" not expanded sets like "{0,5,10,15,20,25,30,35,40,45,50,55}".

    This migration converts any crontabs with curly brace syntax to proper
    cron expressions so periodic tasks will actually execute.
    """
    CrontabSchedule = apps.get_model("django_celery_beat", "CrontabSchedule")

    # Get all crontab schedules
    for crontab in CrontabSchedule.objects.all():
        changed = False

        # Fix minute field
        if crontab.minute and "{" in crontab.minute:
            # Handle patterns like {0,5,10,...} which should be */5
            if crontab.minute.startswith("{0,") or crontab.minute.startswith("{0}"):
                # Check if it's every N minutes
                parts = crontab.minute.strip("{}").split(",")
                if len(parts) > 1 and all(p.isdigit() for p in parts):
                    try:
                        # Calculate interval
                        interval = int(parts[1]) - int(parts[0])
                        if interval > 0:
                            crontab.minute = f"*/{interval}"
                            changed = True
                    except (ValueError, IndexError):
                        pass

        # Fix hour field
        if crontab.hour and "{" in crontab.hour:
            # Handle patterns like {0,8,16} which should be */8
            parts = crontab.hour.strip("{}").split(",")
            if len(parts) > 1 and all(p.isdigit() for p in parts):
                try:
                    interval = int(parts[1]) - int(parts[0])
                    if interval > 0:
                        crontab.hour = f"*/{interval}"
                        changed = True
                except (ValueError, IndexError):
                    pass
            elif len(parts) == 1:
                # Single value like {6}
                crontab.hour = parts[0]
                changed = True

        # Fix day_of_week field - {0,1,2,3,4,5,6} should be *
        if crontab.day_of_week and "{" in crontab.day_of_week:
            parts = crontab.day_of_week.strip("{}").split(",")
            if len(parts) == 7:  # All days
                crontab.day_of_week = "*"
                changed = True

        # Fix day_of_month field - {1,2,3,...,31} should be *
        if crontab.day_of_month and "{" in crontab.day_of_month:
            parts = crontab.day_of_month.strip("{}").split(",")
            if len(parts) >= 28:  # Most/all days
                crontab.day_of_month = "*"
                changed = True

        # Fix month_of_year field - {1,2,...,12} should be *
        if crontab.month_of_year and "{" in crontab.month_of_year:
            parts = crontab.month_of_year.strip("{}").split(",")
            if len(parts) == 12:  # All months
                crontab.month_of_year = "*"
                changed = True

        if changed:
            crontab.save()


class Migration(migrations.Migration):

    dependencies = [
        ("library_manager", "0010_auto_20250924_1707"),
        ("django_celery_beat", "__latest__"),  # Ensure django_celery_beat tables exist
    ]

    operations = [
        migrations.RunPython(fix_crontab_schedules, migrations.RunPython.noop),
    ]
