# Generated by Django 5.2.6 on 2025-11-17 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("library_manager", "0011_fix_crontab_schedules"),
    ]

    operations = [
        migrations.AddField(
            model_name="artist",
            name="last_downloaded_at",
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
