# Generated by Django 5.2.6 on 2025-11-19 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("library_manager", "0012_artist_last_downloaded_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpotifyOAuthToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("access_token", models.TextField()),
                ("refresh_token", models.TextField()),
                ("token_type", models.CharField(default="Bearer", max_length=50)),
                ("expires_at", models.DateTimeField()),
                (
                    "scope",
                    models.TextField(
                        default="playlist-read-private user-library-read user-follow-read"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "spotify_oauth_tokens",
            },
        ),
        migrations.AlterField(
            model_name="album",
            name="spotify_gid",
            field=models.CharField(
                help_text="Spotify Album ID (22-char base62, e.g., '7K3BhSpAxZBzniskgIPUYj')",
                max_length=2048,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="artist",
            name="gid",
            field=models.CharField(
                help_text="Spotify Artist ID (22-char base62, e.g., '4iV5W9uYEdYUVa79Axb7Rh')",
                max_length=120,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="song",
            name="gid",
            field=models.CharField(
                help_text="Spotify Track ID (22-char base62, e.g., '6rqhFgbbKwnb9MLmUQDhG6')",
                max_length=120,
                unique=True,
            ),
        ),
    ]
