# Generated by Django 5.2.6 on 2025-11-20 19:37

import re

from django.db import migrations


def normalize_spotify_url(url: str) -> str:
    """Convert various Spotify URL formats to a standard format, stripping tracking parameters."""
    # Handle spotify: URIs (already normalized)
    if url.startswith("spotify:"):
        return url

    # Handle web URLs - extract content type and ID, ignoring parameters
    if "open.spotify.com" in url:
        match = re.search(r"open\.spotify\.com/([^/?]+)/([^/?]+)", url)
        if match:
            content_type, content_id = match.groups()
            return f"spotify:{content_type}:{content_id}"

    return url


def normalize_playlist_urls(apps, schema_editor):  # type: ignore[no-untyped-def]
    """Normalize all existing TrackedPlaylist URLs by removing tracking parameters."""
    TrackedPlaylist = apps.get_model("library_manager", "TrackedPlaylist")

    updated_count = 0
    for playlist in TrackedPlaylist.objects.all():
        original_url = playlist.url
        normalized_url = normalize_spotify_url(original_url)

        if original_url != normalized_url:
            playlist.url = normalized_url
            playlist.save()
            updated_count += 1

    if updated_count > 0:
        print(f"Normalized {updated_count} playlist URL(s)")


def reverse_normalize(apps, schema_editor):  # type: ignore[no-untyped-def]
    """Reverse migration - no-op as we can't restore original URLs."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("library_manager", "0013_add_spotify_oauth_token"),
    ]

    operations = [
        migrations.RunPython(normalize_playlist_urls, reverse_normalize),
    ]
