# Generated by Django 5.2.6 on 2025-11-21 00:54

import re

from django.db import migrations


def convert_hex_gid_to_base62(hex_gid: str) -> str | None:
    """
    Convert hex-encoded Spotify GID to base62 format.

    Copied from library_manager.validators to avoid import dependencies in migration.
    """
    if not hex_gid or len(hex_gid) != 32:
        return None

    # Validate it's actually hex
    if not re.match(r"^[a-f0-9]{32}$", hex_gid.lower()):
        return None

    try:
        import base62  # type: ignore[import-untyped]

        # Convert hex string to integer
        gid_int = int(hex_gid, 16)

        # Encode as base62 using inverted charset (for Spotify compatibility)
        base62_id = base62.encode(gid_int, charset=base62.CHARSET_INVERTED)

        # Pad to 22 characters
        return str(base62_id).zfill(22)
    except (ValueError, ImportError):
        return None


def is_valid_base62_id(spotify_id: str) -> bool:
    """Check if string is a valid 22-char base62 Spotify ID."""
    if not spotify_id or not isinstance(spotify_id, str):
        return False

    if len(spotify_id) != 22:
        return False

    # Must be alphanumeric only (base62 charset)
    return spotify_id.isalnum()


def normalize_artist_gids(apps, schema_editor):  # type: ignore[no-untyped-def]
    """Normalize all Artist GIDs from hex to base62 format."""
    Artist = apps.get_model("library_manager", "Artist")
    from django.db import connection

    artists_deleted = 0
    artists_updated = 0
    albums_updated = 0

    # Get all artists with hex GIDs
    hex_artists = [a for a in Artist.objects.all() if len(a.gid) == 32]

    for artist in hex_artists:
        original_gid = artist.gid
        normalized_gid = convert_hex_gid_to_base62(original_gid)

        if normalized_gid:
            # Check if an artist with the normalized GID already exists
            existing_artist = Artist.objects.filter(gid=normalized_gid).first()

            if existing_artist:
                # Duplicate exists - update albums to reference the existing artist, then delete this one
                with connection.cursor() as cursor:
                    cursor.execute(
                        "UPDATE albums SET artist_gid = %s WHERE artist_gid = %s",
                        [normalized_gid, original_gid],
                    )
                    album_count = cursor.rowcount
                    albums_updated += album_count

                # Delete the duplicate hex artist
                artist.delete()
                artists_deleted += 1
            else:
                # No duplicate - just update the GID
                artist.gid = normalized_gid
                artist.save()
                artists_updated += 1

                # Update albums
                with connection.cursor() as cursor:
                    cursor.execute(
                        "UPDATE albums SET artist_gid = %s WHERE artist_gid = %s",
                        [normalized_gid, original_gid],
                    )
                    album_count = cursor.rowcount
                    albums_updated += album_count

    if artists_updated > 0:
        print(f"Normalized {artists_updated} artist GID(s)")
    if artists_deleted > 0:
        print(f"Deleted {artists_deleted} duplicate artist(s)")
    if albums_updated > 0:
        print(f"Updated {albums_updated} album artist references")


def normalize_song_gids(apps, schema_editor):  # type: ignore[no-untyped-def]
    """Normalize all Song GIDs from hex to base62 format."""
    Song = apps.get_model("library_manager", "Song")

    songs_deleted = 0
    songs_updated = 0

    # Get all songs with hex GIDs
    hex_songs = [s for s in Song.objects.all() if len(s.gid) == 32]

    for song in hex_songs:
        original_gid = song.gid
        normalized_gid = convert_hex_gid_to_base62(original_gid)

        if normalized_gid:
            # Check if a song with the normalized GID already exists
            existing_song = Song.objects.filter(gid=normalized_gid).first()

            if existing_song:
                # Duplicate exists - delete this hex version
                song.delete()
                songs_deleted += 1
            else:
                # No duplicate - just update the GID
                song.gid = normalized_gid
                song.save()
                songs_updated += 1

    if songs_updated > 0:
        print(f"Normalized {songs_updated} song GID(s)")
    if songs_deleted > 0:
        print(f"Deleted {songs_deleted} duplicate song(s)")


def reverse_normalize(apps, schema_editor):  # type: ignore[no-untyped-def]
    """Reverse migration - no-op as we can't restore original GIDs."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("library_manager", "0014_normalize_playlist_urls"),
    ]

    operations = [
        migrations.RunPython(normalize_artist_gids, reverse_normalize),
        migrations.RunPython(normalize_song_gids, reverse_normalize),
    ]
