# Generated by Django 5.2.6 on 2025-11-25 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("library_manager", "0015_normalize_gids"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="last_download_attempt",
            field=models.DateTimeField(
                blank=True,
                help_text="When the song was last queued for download",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="album",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
