# Generated by Django 5.2.6 on 2025-11-25 03:12

from django.db import migrations


def clear_periodic_tasks(apps, schema_editor):
    """
    Clear all periodic task entries from django_celery_beat.

    Celery Beat will recreate them from CELERY_BEAT_SCHEDULE on startup.
    This ensures a clean slate and removes any stale/orphaned entries.
    """
    try:
        PeriodicTask = apps.get_model("django_celery_beat", "PeriodicTask")
        CrontabSchedule = apps.get_model("django_celery_beat", "CrontabSchedule")
        IntervalSchedule = apps.get_model("django_celery_beat", "IntervalSchedule")
    except LookupError:
        # django_celery_beat not installed, skip
        return

    # Delete all periodic tasks - they'll be recreated from code config
    PeriodicTask.objects.all().delete()
    # Clean up orphaned schedules
    CrontabSchedule.objects.all().delete()
    IntervalSchedule.objects.all().delete()


def reverse_clear(apps, schema_editor):
    """Reverse is a no-op - Celery Beat will recreate tasks on startup."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("library_manager", "0016_add_last_download_attempt_to_song"),
    ]

    operations = [
        migrations.RunPython(clear_periodic_tasks, reverse_clear),
    ]
