# Generated by Django 5.2.8 on 2025-11-27 02:40

from django.db import migrations, models


def migrate_enabled_to_status(apps, schema_editor):
    """Migrate existing enabled field to new status field."""
    TrackedPlaylist = apps.get_model("library_manager", "TrackedPlaylist")

    # Update disabled playlists to 'disabled_by_user' status
    TrackedPlaylist.objects.filter(enabled=False).update(status="disabled_by_user")

    # Enabled playlists already have default 'active' status


def migrate_status_to_enabled(apps, schema_editor):
    """Reverse migration: convert status back to enabled field."""
    TrackedPlaylist = apps.get_model("library_manager", "TrackedPlaylist")

    # Only 'active' status maps to enabled=True
    TrackedPlaylist.objects.filter(status="active").update(enabled=True)
    TrackedPlaylist.objects.exclude(status="active").update(enabled=False)


class Migration(migrations.Migration):

    dependencies = [
        ("library_manager", "0017_clear_periodic_task_entries"),
    ]

    operations = [
        # Step 1: Add new fields first (with defaults)
        migrations.AddField(
            model_name="trackedplaylist",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("disabled_by_user", "Disabled by user"),
                    (
                        "spotify_api_restricted",
                        "Spotify API restricted (algorithmic playlists)",
                    ),
                    ("not_found", "Not found (deleted or private)"),
                ],
                default="active",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="trackedplaylist",
            name="status_message",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        # Step 2: Migrate data from enabled to status
        migrations.RunPython(migrate_enabled_to_status, migrate_status_to_enabled),
        # Step 3: Remove the old enabled field
        migrations.RemoveField(
            model_name="trackedplaylist",
            name="enabled",
        ),
    ]
