# Generated by Django 5.2.8 on 2025-11-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("library_manager", "0018_add_playlist_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="trackedplaylist",
            name="snapshot_id",
            field=models.CharField(
                blank=True,
                help_text="Spotify playlist version identifier for efficient change detection",
                max_length=255,
                null=True,
            ),
        ),
    ]
