# Generated by Django 5.2.8 on 2025-11-27 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("library_manager", "0019_add_snapshot_id_to_tracked_playlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="failure_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("temporary", "Temporary error (network, rate limit, auth)"),
                    ("spotify_404", "Song not found on Spotify"),
                    ("ytm_no_match", "No YouTube Music match found"),
                    ("both_unavailable", "Unavailable on both Spotify and YTM"),
                ],
                help_text="Categorized reason for last failure (NULL = no failure)",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="song",
            name="last_failed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the song last failed (for exponential backoff calculation)",
                null=True,
            ),
        ),
    ]
