# Generated by Django 5.2.8 on 2025-12-08 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("library_manager", "0020_add_failure_reason_and_last_failed_at_to_song"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="isrc",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="International Standard Recording Code (e.g., 'USRC11234567')",
                max_length=20,
                null=True,
            ),
        ),
    ]
