# Generated by Django 5.2.8 on 2025-12-09 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("library_manager", "0021_add_isrc_to_song"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="album",
            field=models.ForeignKey(
                blank=True,
                help_text="Album this song belongs to (nullable for legacy songs pending backfill)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="songs",
                to="library_manager.album",
            ),
        ),
    ]
