# Generated by Django 5.2.8 on 2025-12-10 00:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("library_manager", "0022_add_album_to_song"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpotifyRateLimitState",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "key",
                    models.CharField(
                        default="spotify_rate_limit", max_length=50, unique=True
                    ),
                ),
                (
                    "last_call_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("window_call_count", models.IntegerField(default=0)),
                (
                    "window_start_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("rate_limited_until", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "spotify_rate_limit_state",
            },
        ),
    ]
