# Generated by Django 5.2.8 on 2025-12-10 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("library_manager", "0023_add_spotify_rate_limit_state"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="taskhistory",
            index=models.Index(
                fields=["-started_at", "-id"], name="task_histor_started_7ed924_idx"
            ),
        ),
    ]
