# Generated by Django 5.2.8 on 2025-12-12 16:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("library_manager", "0024_add_task_history_started_at_id_index"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="spotifyratelimitstate",
            name="window_call_count",
        ),
        migrations.RemoveField(
            model_name="spotifyratelimitstate",
            name="window_start_at",
        ),
        migrations.AddField(
            model_name="spotifyratelimitstate",
            name="backoff_pressure",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="spotifyratelimitstate",
            name="burst_call_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="spotifyratelimitstate",
            name="burst_window_start",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="spotifyratelimitstate",
            name="hourly_call_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="spotifyratelimitstate",
            name="hourly_window_start",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="spotifyratelimitstate",
            name="last_pressure_decay",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="spotifyratelimitstate",
            name="sustained_call_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="spotifyratelimitstate",
            name="sustained_window_start",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
