# Generated by Django 5.2.8 on 2025-12-16 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("library_manager", "0025_multi_tier_rate_limit"),
    ]

    operations = [
        migrations.CreateModel(
            name="PendingMetadataUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.BigIntegerField(help_text="ID of the entity")),
                (
                    "field_name",
                    models.CharField(
                        default="name",
                        help_text="Field that changed (currently only 'name' supported)",
                        max_length=50,
                    ),
                ),
                (
                    "old_value",
                    models.CharField(
                        help_text="Value at time of download", max_length=500
                    ),
                ),
                (
                    "new_value",
                    models.CharField(
                        help_text="Current value from Spotify", max_length=500
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("applied", "Applied"),
                            ("dismissed", "Dismissed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("detected_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        help_text="Type of entity (Artist, Album, or Song)",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "db_table": "pending_metadata_updates",
                "indexes": [
                    models.Index(
                        fields=["status"], name="pending_met_status_270abd_idx"
                    ),
                    models.Index(
                        fields=["content_type", "status"],
                        name="pending_met_content_12e821_idx",
                    ),
                    models.Index(
                        fields=["detected_at"], name="pending_met_detecte_a66936_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("content_type", "object_id", "field_name"),
                        name="unique_pending_update_per_entity_field",
                    )
                ],
            },
        ),
    ]
