# Generated by Django 5.2.8 on 2026-01-07 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("library_manager", "0026_add_pending_metadata_update"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Metric name, e.g., 'fallback.tidal.success'",
                        max_length=100,
                    ),
                ),
                (
                    "metric_type",
                    models.CharField(
                        choices=[("counter", "Counter"), ("gauge", "Gauge")],
                        default="counter",
                        max_length=20,
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=6, help_text="Metric value", max_digits=20
                    ),
                ),
                (
                    "labels",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional labels for filtering, e.g., {'provider': 'tidal'}",
                    ),
                ),
                ("recorded_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "db_table": "app_metrics",
                "indexes": [
                    models.Index(
                        fields=["name", "recorded_at"],
                        name="app_metrics_name_895838_idx",
                    ),
                    models.Index(
                        fields=["recorded_at"], name="app_metrics_recorde_4a9e2f_idx"
                    ),
                ],
            },
        ),
    ]
