# Generated by Django 5.2.8 on 2026-01-08 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("library_manager", "0027_add_app_metric"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="download_provider",
            field=models.SmallIntegerField(
                choices=[
                    (0, "Unknown"),
                    (1, "spotdl (YouTube Music)"),
                    (2, "Tidal"),
                    (3, "Qobuz"),
                ],
                default=1,
                help_text="Provider used to download this song",
            ),
        ),
        migrations.CreateModel(
            name="SongUpgradeAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.SmallIntegerField(
                        choices=[
                            (0, "Unknown"),
                            (1, "spotdl (YouTube Music)"),
                            (2, "Tidal"),
                            (3, "Qobuz"),
                        ],
                        help_text="Provider that was attempted",
                    ),
                ),
                ("attempted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "result",
                    models.SmallIntegerField(
                        choices=[
                            (0, "Song not available on provider"),
                            (1, "Provider API error (temporary - can retry)"),
                            (2, "Downloaded file was not higher quality"),
                            (3, "Successfully upgraded"),
                        ],
                        help_text="Outcome of the upgrade attempt",
                    ),
                ),
                (
                    "original_bitrate",
                    models.IntegerField(
                        blank=True,
                        help_text="Bitrate of the song before this attempt",
                        null=True,
                    ),
                ),
                (
                    "new_bitrate",
                    models.IntegerField(
                        blank=True,
                        help_text="Bitrate of downloaded file (if download succeeded)",
                        null=True,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Error details for failed attempts",
                    ),
                ),
                (
                    "song",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="upgrade_attempts",
                        to="library_manager.song",
                    ),
                ),
            ],
            options={
                "db_table": "song_upgrade_attempts",
                "indexes": [
                    models.Index(
                        fields=["song", "provider"],
                        name="song_upgrad_song_id_34600c_idx",
                    ),
                    models.Index(
                        fields=["result"], name="song_upgrad_result_f9c415_idx"
                    ),
                    models.Index(
                        fields=["attempted_at"], name="song_upgrad_attempt_f31533_idx"
                    ),
                ],
            },
        ),
    ]
