# Generated by Django 5.2.8 on 2026-01-23 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("library_manager", "0028_add_download_provider_and_upgrade_attempts"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("alert_type", models.CharField(max_length=50, unique=True)),
                ("last_sent_at", models.DateTimeField()),
                ("last_message", models.TextField(blank=True, default="")),
            ],
            options={
                "db_table": "notification_state",
            },
        ),
    ]
