# Generated by Django 5.2.8 on 2026-02-05 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("library_manager", "0029_notification_state"),
    ]

    operations = [
        migrations.CreateModel(
            name="APIRateLimitState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("api_name", models.CharField(max_length=50, unique=True)),
                ("max_requests_per_second", models.FloatField()),
                ("is_rate_limited", models.BooleanField(default=False)),
                ("limited_until", models.DateTimeField(blank=True, null=True)),
                ("request_count", models.IntegerField(default=0)),
                ("window_start", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "api_rate_limit_state",
            },
        ),
        migrations.CreateModel(
            name="TrackMappingCache",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "musicbrainz_id",
                    models.CharField(blank=True, max_length=36, null=True, unique=True),
                ),
                (
                    "name_lookup_key",
                    models.CharField(
                        blank=True, max_length=1024, null=True, unique=True
                    ),
                ),
                (
                    "spotify_track_id",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                ("isrc", models.CharField(blank=True, max_length=20, null=True)),
                ("confidence", models.FloatField(default=1.0)),
                ("mapping_method", models.CharField(max_length=30)),
                ("no_match", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "track_mapping_cache",
            },
        ),
        migrations.CreateModel(
            name="ExternalList",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=500)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("lastfm", "Last.fm"),
                            ("listenbrainz", "ListenBrainz"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "list_type",
                    models.CharField(
                        choices=[
                            ("loved", "Loved/Favorited Tracks"),
                            ("top", "Top Tracks"),
                            ("playlist", "Playlist"),
                            ("chart", "Chart"),
                        ],
                        max_length=20,
                    ),
                ),
                ("username", models.CharField(max_length=255)),
                ("period", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "list_identifier",
                    models.CharField(
                        blank=True,
                        help_text="Source-specific ID: ListenBrainz playlist MBID, chart tag, country code, or 'global'",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("disabled_by_user", "Disabled by user"),
                            ("auth_error", "Authentication error"),
                            ("not_found", "User not found"),
                        ],
                        default="active",
                        max_length=30,
                    ),
                ),
                (
                    "status_message",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("auto_track_artists", models.BooleanField(default=False)),
                (
                    "content_hash",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("total_tracks", models.IntegerField(default=0)),
                ("mapped_tracks", models.IntegerField(default=0)),
                ("failed_tracks", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "external_lists",
                "unique_together": {
                    ("source", "list_type", "username", "period", "list_identifier")
                },
            },
        ),
        migrations.CreateModel(
            name="ExternalListTrack",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("artist_name", models.CharField(max_length=500)),
                ("track_name", models.CharField(max_length=500)),
                (
                    "musicbrainz_id",
                    models.CharField(blank=True, max_length=36, null=True),
                ),
                (
                    "mapping_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending mapping"),
                            ("mapped", "Successfully mapped to Spotify"),
                            ("failed", "Mapping failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "spotify_track_id",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                ("mapping_confidence", models.FloatField(blank=True, null=True)),
                (
                    "mapping_method",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "mapping_error",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("mapped_at", models.DateTimeField(blank=True, null=True)),
                (
                    "external_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracks",
                        to="library_manager.externallist",
                    ),
                ),
                (
                    "song",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="library_manager.song",
                    ),
                ),
            ],
            options={
                "db_table": "external_list_tracks",
                "indexes": [
                    models.Index(
                        fields=["mapping_status"], name="external_li_mapping_651ce1_idx"
                    ),
                    models.Index(
                        fields=["external_list", "mapping_status"],
                        name="external_li_externa_2d6596_idx",
                    ),
                    models.Index(
                        fields=["spotify_track_id"],
                        name="external_li_spotify_0dad20_idx",
                    ),
                ],
                "unique_together": {("external_list", "artist_name", "track_name")},
            },
        ),
    ]
