# Generated by Django 5.2.10 on 2026-02-05 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("library_manager", "0030_add_external_list_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="externallist",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("disabled_by_user", "Disabled by user"),
                    ("auth_error", "Authentication error"),
                    ("not_found", "User not found"),
                    ("sync_error", "Sync error"),
                ],
                default="active",
                max_length=30,
            ),
        ),
    ]
