# Generated by Django 5.2.10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("library_manager", "0031_add_sync_error_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="externallist",
            name="source",
            field=models.CharField(
                choices=[
                    ("lastfm", "Last.fm"),
                    ("listenbrainz", "ListenBrainz"),
                    ("youtube_music", "YouTube Music"),
                ],
                max_length=30,
            ),
        ),
    ]
