# Generated by Django 5.2.10 on 2026-02-05 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("library_manager", "0032_add_youtube_music_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="externallist",
            name="source",
            field=models.CharField(
                choices=[
                    ("lastfm", "Last.fm"),
                    ("listenbrainz", "ListenBrainz"),
                    ("youtube_music", "YouTube Music"),
                ],
                max_length=20,
            ),
        ),
    ]
