# Generated by Django 5.2.10 on 2026-03-02 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("library_manager", "0036_album_artist_fk_step2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="spotify_uri",
            field=models.CharField(blank=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name="song",
            name="download_provider",
            field=models.SmallIntegerField(
                choices=[
                    (0, "Unknown"),
                    (1, "spotdl (YouTube Music)"),
                    (2, "Tidal"),
                    (3, "Qobuz"),
                    (4, "YouTube Music (yt-dlp)"),
                ],
                default=1,
                help_text="Provider used to download this song",
            ),
        ),
        migrations.AlterField(
            model_name="songupgradeattempt",
            name="provider",
            field=models.SmallIntegerField(
                choices=[
                    (0, "Unknown"),
                    (1, "spotdl (YouTube Music)"),
                    (2, "Tidal"),
                    (3, "Qobuz"),
                    (4, "YouTube Music (yt-dlp)"),
                ],
                help_text="Provider that was attempted",
            ),
        ),
    ]
