# Generated by Django 5.2.10 on 2026-03-02 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("library_manager", "0037_album_spotify_uri_blank_true"),
    ]

    operations = [
        migrations.AddField(
            model_name="artist",
            name="deezer_migration_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending", "Pending"),
                    ("in_progress", "In Progress"),
                    ("complete", "Complete"),
                    ("failed", "Failed"),
                ],
                db_index=True,
                max_length=20,
                null=True,
            ),
        ),
    ]
