# Generated by Django 5.2.10 on 2026-03-02 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("library_manager", "0038_artist_deezer_migration_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="trackedplaylist",
            name="provider",
            field=models.CharField(
                choices=[("spotify", "Spotify"), ("deezer", "Deezer")],
                default="spotify",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="trackedplaylist",
            name="snapshot_id",
            field=models.CharField(
                blank=True,
                help_text="Provider-specific change detection value (Spotify snapshot_id or Deezer checksum)",
                max_length=255,
                null=True,
            ),
        ),
    ]
