# Generated by Django 5.2.10 on 2026-03-05 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("library_manager", "0039_playlist_provider_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="trackmappingcache",
            name="deezer_track_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
