# Generated by Django 5.2.10 on 2026-03-06 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("library_manager", "0040_add_deezer_track_id_to_trackmappingcache"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song",
            name="download_provider",
            field=models.SmallIntegerField(
                choices=[
                    (0, "Unknown"),
                    (1, "YouTube Music (legacy)"),
                    (2, "Tidal"),
                    (3, "Qobuz"),
                    (4, "YouTube Music (yt-dlp)"),
                ],
                default=1,
                help_text="Provider used to download this song",
            ),
        ),
        migrations.AlterField(
            model_name="songupgradeattempt",
            name="provider",
            field=models.SmallIntegerField(
                choices=[
                    (0, "Unknown"),
                    (1, "YouTube Music (legacy)"),
                    (2, "Tidal"),
                    (3, "Qobuz"),
                    (4, "YouTube Music (yt-dlp)"),
                ],
                help_text="Provider that was attempted",
            ),
        ),
    ]
