# Generated by Django 5.2.10 on 2026-03-10 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("library_manager", "0041_alter_song_download_provider_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="failure_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("temporary", "Temporary error (network, rate limit, auth)"),
                    ("partial", "Some tracks downloaded but not all"),
                    ("all_unavailable", "All tracks failed on all providers"),
                    (
                        "deezer_no_tracks",
                        "Deezer returned no tracks (deleted/region-locked)",
                    ),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="album",
            name="last_failed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="album",
            name="unavailable",
            field=models.BooleanField(default=False),
        ),
    ]
