# Generated by Django 5.2.10 on 2026-03-23 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("library_manager", "0042_album_failure_tracking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song",
            name="download_provider",
            field=models.SmallIntegerField(
                choices=[
                    (0, "Unknown"),
                    (1, "YouTube Music (legacy)"),
                    (2, "Tidal"),
                    (3, "Qobuz"),
                    (4, "YouTube Music (yt-dlp)"),
                    (5, "Monochrome (Tidal CDN)"),
                ],
                default=1,
                help_text="Provider used to download this song",
            ),
        ),
        migrations.AlterField(
            model_name="songupgradeattempt",
            name="provider",
            field=models.SmallIntegerField(
                choices=[
                    (0, "Unknown"),
                    (1, "YouTube Music (legacy)"),
                    (2, "Tidal"),
                    (3, "Qobuz"),
                    (4, "YouTube Music (yt-dlp)"),
                    (5, "Monochrome (Tidal CDN)"),
                ],
                help_text="Provider that was attempted",
            ),
        ),
        migrations.CreateModel(
            name="SongLyricsStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("has_lyrics", models.BooleanField(default=False)),
                ("last_attempt", models.DateTimeField(blank=True, null=True)),
                ("attempt_count", models.IntegerField(default=0)),
                (
                    "song",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lyrics_status",
                        to="library_manager.song",
                    ),
                ),
            ],
            options={
                "db_table": "song_lyrics_status",
            },
        ),
        migrations.CreateModel(
            name="PlaylistSong",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("track_order", models.IntegerField()),
                (
                    "playlist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="playlist_songs",
                        to="library_manager.trackedplaylist",
                    ),
                ),
                (
                    "song",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="playlist_entries",
                        to="library_manager.song",
                    ),
                ),
            ],
            options={
                "db_table": "playlist_songs",
                "ordering": ["track_order"],
                "unique_together": {("playlist", "song")},
            },
        ),
    ]
