# Generated by Django 5.2.10 on 2026-03-24 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("library_manager", "0043_add_song_lyrics_status_and_playlist_song"),
    ]

    operations = [
        migrations.AddField(
            model_name="trackedplaylist",
            name="m3u_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Generate .m3u playlist file for media server import",
            ),
        ),
    ]
