# Generated by Django 5.2.10 on 2026-03-26 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("library_manager", "0044_add_playlist_m3u_enabled"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="songlyricsstatus",
            index=models.Index(
                condition=models.Q(("has_lyrics", False)),
                fields=["attempt_count", "id"],
                name="idx_lyrics_pending_retry",
            ),
        ),
    ]
