# Generated by Django 5.2.10 on 2026-03-31 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("library_manager", "0046_add_app_setting"),
    ]

    operations = [
        migrations.CreateModel(
            name="CachedStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(db_index=True, max_length=100, unique=True)),
                ("display_name", models.CharField(max_length=200)),
                ("value", models.JSONField()),
                ("category", models.CharField(db_index=True, max_length=50)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "cached_stats",
            },
        ),
        migrations.AlterField(
            model_name="song",
            name="download_provider",
            field=models.SmallIntegerField(
                choices=[
                    (0, "Unknown"),
                    (1, "YouTube Music (legacy)"),
                    (2, "Tidal"),
                    (3, "Qobuz"),
                    (4, "YouTube Music (yt-dlp)"),
                    (5, "Monochrome (Tidal CDN)"),
                ],
                default=0,
                help_text="Provider used to download this song",
            ),
        ),
    ]
