# Generated by Django 5.2.8 on 2026-04-06 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("library_manager", "0047_cachedstat_alter_song_download_provider"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="song",
            name="idx_song_deezer_id",
        ),
        migrations.AlterField(
            model_name="song",
            name="deezer_id",
            field=models.BigIntegerField(
                blank=True, db_index=True, help_text="Deezer track ID", null=True
            ),
        ),
        migrations.AddConstraint(
            model_name="song",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("album__isnull", False), ("deezer_id__isnull", False)
                ),
                fields=("deezer_id", "album"),
                name="unique_song_per_album",
            ),
        ),
    ]
