# Generated by Django 5.2.10 on 2026-04-07 15:46

from django.db import migrations, models


def migrate_tracking_data(apps, schema_editor):
    Artist = apps.get_model("library_manager", "Artist")
    Artist.objects.filter(tracked=True).update(tracking_tier=1)

    TrackedPlaylist = apps.get_model("library_manager", "TrackedPlaylist")
    TrackedPlaylist.objects.filter(auto_track_artists=True).update(auto_track_tier=1)

    ExternalList = apps.get_model("library_manager", "ExternalList")
    ExternalList.objects.filter(auto_track_artists=True).update(auto_track_tier=1)


def reverse_tracking_data(apps, schema_editor):
    Artist = apps.get_model("library_manager", "Artist")
    Artist.objects.filter(tracking_tier__gte=1).update(tracked=True)
    Artist.objects.filter(tracking_tier=0).update(tracked=False)

    TrackedPlaylist = apps.get_model("library_manager", "TrackedPlaylist")
    TrackedPlaylist.objects.filter(auto_track_tier__isnull=False).update(
        auto_track_artists=True
    )
    TrackedPlaylist.objects.filter(auto_track_tier__isnull=True).update(
        auto_track_artists=False
    )

    ExternalList = apps.get_model("library_manager", "ExternalList")
    ExternalList.objects.filter(auto_track_tier__isnull=False).update(
        auto_track_artists=True
    )
    ExternalList.objects.filter(auto_track_tier__isnull=True).update(
        auto_track_artists=False
    )


class Migration(migrations.Migration):

    dependencies = [
        ("library_manager", "0048_song_deezer_id_per_album_unique"),
    ]

    operations = [
        # Step 1: Add new fields (with safe defaults so existing rows get tier=0/NULL)
        migrations.AddField(
            model_name="artist",
            name="tracking_tier",
            field=models.SmallIntegerField(
                choices=[(0, "Untracked"), (1, "Tracked"), (2, "Favourite")],
                db_index=True,
                default=0,
                help_text="0=Untracked, 1=Tracked, 2=Favourite",
            ),
        ),
        migrations.AddField(
            model_name="externallist",
            name="auto_track_tier",
            field=models.SmallIntegerField(
                blank=True,
                choices=[(0, "Untracked"), (1, "Tracked"), (2, "Favourite")],
                default=None,
                help_text="None=off, 1=Tracked, 2=Favourite. Tier assigned to auto-discovered artists.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="trackedplaylist",
            name="auto_track_tier",
            field=models.SmallIntegerField(
                blank=True,
                choices=[(0, "Untracked"), (1, "Tracked"), (2, "Favourite")],
                default=None,
                help_text="None=off, 1=Tracked, 2=Favourite. Tier assigned to auto-discovered artists.",
                null=True,
            ),
        ),
        # Step 2: Migrate boolean data to tier values
        migrations.RunPython(migrate_tracking_data, reverse_tracking_data),
        # Step 3: Remove old fields and index
        migrations.RemoveIndex(
            model_name="artist",
            name="artists_tracked_692424_idx",
        ),
        migrations.RemoveField(
            model_name="artist",
            name="tracked",
        ),
        migrations.RemoveField(
            model_name="externallist",
            name="auto_track_artists",
        ),
        migrations.RemoveField(
            model_name="trackedplaylist",
            name="auto_track_artists",
        ),
    ]
