# Generated by Django 5.2.10 on 2026-05-14 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("library_manager", "0050_cleanup_beat_schedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationstate",
            name="consecutive_failures",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="notificationstate",
            name="last_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
