# Generated by Django 5.2.10 on 2026-05-19 20:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("library_manager", "0051_notification_2strike_counter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="downloadhistory",
            name="progress",
            field=models.SmallIntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1000),
                ],
            ),
        ),
    ]
