# Generated by Django 5.2.10 on 2026-05-22 18:13

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("library_manager", "0052_alter_downloadhistory_progress"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="alternate_isrcs",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=20),
                blank=True,
                default=list,
                help_text="Additional ISRCs that map to this same recording on other platforms (e.g. Apple assigns a different ISRC than Spotify). Lets a cross-platform import match this row without re-searching.",
                size=None,
            ),
        ),
        migrations.AddIndex(
            model_name="song",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["alternate_isrcs"], name="idx_song_alt_isrcs"
            ),
        ),
    ]
