from django.db import IntegrityError

import pytest
from queuetip.models import (
    Account,
    AuthIdentity,
    Contribution,
    Playlist,
    PlaylistMembership,
    Vote,
)
from tests.factories import ArtistFactory, SongFactory


@pytest.mark.django_db
def test_invite_token_autogenerated_and_unique():
    a = Account.objects.create(display_name="Owner")
    p1 = Playlist.objects.create(name="One", created_by=a)
    p2 = Playlist.objects.create(name="Two", created_by=a)
    assert p1.invite_token
    assert p1.invite_token != p2.invite_token


@pytest.mark.django_db
def test_auth_identity_provider_identifier_unique():
    a = Account.objects.create(display_name="Owner")
    AuthIdentity.objects.create(account=a, provider="magic_link", identifier="x@y.z")
    with pytest.raises(IntegrityError):
        AuthIdentity.objects.create(
            account=a, provider="magic_link", identifier="x@y.z"
        )


@pytest.mark.django_db
def test_contribution_unique_per_playlist_song():
    a = Account.objects.create(display_name="Owner")
    p = Playlist.objects.create(name="P", created_by=a)
    song = SongFactory(primary_artist=ArtistFactory())
    Contribution.objects.create(playlist=p, song=song, contributed_by=a)
    with pytest.raises(IntegrityError):
        Contribution.objects.create(playlist=p, song=song, contributed_by=a)


@pytest.mark.django_db
def test_vote_value_check_constraint_rejects_zero():
    a = Account.objects.create(display_name="Owner")
    p = Playlist.objects.create(name="P", created_by=a)
    song = SongFactory(primary_artist=ArtistFactory())
    c = Contribution.objects.create(playlist=p, song=song, contributed_by=a)
    with pytest.raises(IntegrityError):
        Vote.objects.create(contribution=c, account=a, value=0)


@pytest.mark.django_db
def test_membership_unique_per_playlist_account():
    a = Account.objects.create(display_name="Owner")
    p = Playlist.objects.create(name="P", created_by=a)
    PlaylistMembership.objects.create(playlist=p, account=a, role="owner")
    with pytest.raises(IntegrityError):
        PlaylistMembership.objects.create(playlist=p, account=a, role="member")
