/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as SongsRouteImport } from './routes/songs'
import { Route as PlaylistsRouteImport } from './routes/playlists'
import { Route as ArtistsRouteImport } from './routes/artists'
import { Route as AlbumsRouteImport } from './routes/albums'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArtistsArtistIdRouteImport } from './routes/artists_.$artistId'

const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SongsRoute = SongsRouteImport.update({
  id: '/songs',
  path: '/songs',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistsRoute = PlaylistsRouteImport.update({
  id: '/playlists',
  path: '/playlists',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistsRoute = ArtistsRouteImport.update({
  id: '/artists',
  path: '/artists',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumsRoute = AlbumsRouteImport.update({
  id: '/albums',
  path: '/albums',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistsArtistIdRoute = ArtistsArtistIdRouteImport.update({
  id: '/artists_/$artistId',
  path: '/artists/$artistId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/albums': typeof AlbumsRoute
  '/artists': typeof ArtistsRoute
  '/playlists': typeof PlaylistsRoute
  '/songs': typeof SongsRoute
  '/tasks': typeof TasksRoute
  '/artists/$artistId': typeof ArtistsArtistIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/albums': typeof AlbumsRoute
  '/artists': typeof ArtistsRoute
  '/playlists': typeof PlaylistsRoute
  '/songs': typeof SongsRoute
  '/tasks': typeof TasksRoute
  '/artists/$artistId': typeof ArtistsArtistIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/albums': typeof AlbumsRoute
  '/artists': typeof ArtistsRoute
  '/playlists': typeof PlaylistsRoute
  '/songs': typeof SongsRoute
  '/tasks': typeof TasksRoute
  '/artists_/$artistId': typeof ArtistsArtistIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/albums'
    | '/artists'
    | '/playlists'
    | '/songs'
    | '/tasks'
    | '/artists/$artistId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/albums'
    | '/artists'
    | '/playlists'
    | '/songs'
    | '/tasks'
    | '/artists/$artistId'
  id:
    | '__root__'
    | '/'
    | '/albums'
    | '/artists'
    | '/playlists'
    | '/songs'
    | '/tasks'
    | '/artists_/$artistId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlbumsRoute: typeof AlbumsRoute
  ArtistsRoute: typeof ArtistsRoute
  PlaylistsRoute: typeof PlaylistsRoute
  SongsRoute: typeof SongsRoute
  TasksRoute: typeof TasksRoute
  ArtistsArtistIdRoute: typeof ArtistsArtistIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/songs': {
      id: '/songs'
      path: '/songs'
      fullPath: '/songs'
      preLoaderRoute: typeof SongsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlists': {
      id: '/playlists'
      path: '/playlists'
      fullPath: '/playlists'
      preLoaderRoute: typeof PlaylistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artists': {
      id: '/artists'
      path: '/artists'
      fullPath: '/artists'
      preLoaderRoute: typeof ArtistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/albums': {
      id: '/albums'
      path: '/albums'
      fullPath: '/albums'
      preLoaderRoute: typeof AlbumsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artists_/$artistId': {
      id: '/artists_/$artistId'
      path: '/artists/$artistId'
      fullPath: '/artists/$artistId'
      preLoaderRoute: typeof ArtistsArtistIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlbumsRoute: AlbumsRoute,
  ArtistsRoute: ArtistsRoute,
  PlaylistsRoute: PlaylistsRoute,
  SongsRoute: SongsRoute,
  TasksRoute: TasksRoute,
  ArtistsArtistIdRoute: ArtistsArtistIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
