# Generated by Django 5.2.10 on 2026-05-19 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("library_manager", "0052_alter_downloadhistory_progress"),
        ("queuetip", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExportSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("parameters", models.JSONField(default=dict)),
                ("rng_seed", models.BigIntegerField()),
                ("warning_message", models.TextField(blank=True)),
                (
                    "playlist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="export_snapshots",
                        to="queuetip.playlist",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="export_snapshots",
                        to="queuetip.account",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExportSnapshotTrack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveIntegerField()),
                (
                    "inclusion_reason",
                    models.CharField(
                        choices=[
                            ("guaranteed", "Guaranteed (net >= t_high)"),
                            ("rolled_in", "Rolled in"),
                            ("topped_up", "Topped up to min_size"),
                        ],
                        max_length=16,
                    ),
                ),
                ("roll_probability", models.FloatField()),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracks",
                        to="queuetip.exportsnapshot",
                    ),
                ),
                (
                    "song",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="queuetip_export_tracks",
                        to="library_manager.song",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("snapshot", "position"),
                        name="queuetip_export_track_position_unique",
                    )
                ],
            },
        ),
    ]
