# Generated by Django 5.2.10 on 2026-05-20 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("queuetip", "0002_exportsnapshot_exportsnapshottrack"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalServiceLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service",
                    models.CharField(choices=[("spotify", "Spotify")], max_length=16),
                ),
                ("access_token", models.TextField()),
                ("refresh_token", models.TextField()),
                ("expires_at", models.DateTimeField()),
                ("scope", models.CharField(blank=True, max_length=512)),
                ("service_user_id", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_service_links",
                        to="queuetip.account",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("account", "service"),
                        name="queuetip_external_service_link_unique",
                    )
                ],
            },
        ),
    ]
