# Generated by Django 5.2.10 on 2026-05-20 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("queuetip", "0003_externalservicelink"),
    ]

    operations = [
        migrations.CreateModel(
            name="MagicLinkRequestLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identifier", models.CharField(max_length=254)),
                ("ip_address", models.CharField(max_length=45)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
    ]
