# Generated by Django 5.2.10 on 2026-05-20 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("queuetip", "0005_uuidify_exportsnapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="session_epoch",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
