# Generated by Django 5.2.10 on 2026-05-20 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("queuetip", "0006_account_session_epoch"),
    ]

    operations = [
        migrations.CreateModel(
            name="QueuetipSignupAllowlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("note", models.CharField(blank=True, max_length=200)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-added_at"],
            },
        ),
    ]
