# Generated by Django 5.2.10 on 2026-05-21 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("queuetip", "0007_queuetipsignupallowlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="bulkimportjob",
            name="total_tracks",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
