# Generated by Django 5.2.10 on 2026-05-21 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("queuetip", "0008_bulkimportjob_total_tracks"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubsonicConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=80)),
                ("server_url", models.URLField(max_length=500)),
                ("username", models.CharField(max_length=120)),
                ("password_encrypted", models.BinaryField()),
                ("last_verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("ok", "Verified"),
                            ("failed", "Failed"),
                            ("unknown", "Not verified"),
                        ],
                        default="unknown",
                        max_length=16,
                    ),
                ),
                ("verification_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subsonic_connections",
                        to="queuetip.account",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlaylistExportTarget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "destination_type",
                    models.CharField(
                        choices=[("spotify", "Spotify"), ("subsonic", "Subsonic")],
                        max_length=16,
                    ),
                ),
                ("remote_playlist_id", models.CharField(blank=True, max_length=200)),
                (
                    "sync_mode",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("on_change", "Auto-sync on changes"),
                        ],
                        default="manual",
                        max_length=16,
                    ),
                ),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_sync_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("ok", "Synced"),
                            ("partial", "Synced (some tracks unmatched)"),
                            ("failed", "Failed"),
                            ("remote_deleted", "Remote deleted — re-link required"),
                        ],
                        default="pending",
                        max_length=24,
                    ),
                ),
                ("last_error", models.TextField(blank=True)),
                ("unmatched_track_titles", models.JSONField(default=list)),
                ("matched_track_count", models.PositiveIntegerField(default=0)),
                ("total_track_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="export_targets",
                        to="queuetip.account",
                    ),
                ),
                (
                    "playlist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="export_targets",
                        to="queuetip.playlist",
                    ),
                ),
                (
                    "spotify_link",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="export_targets",
                        to="queuetip.externalservicelink",
                    ),
                ),
                (
                    "subsonic_connection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="export_targets",
                        to="queuetip.subsonicconnection",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="subsonicconnection",
            constraint=models.UniqueConstraint(
                fields=("account",),
                name="queuetip_subsonic_connection_unique_per_account",
            ),
        ),
        migrations.AddIndex(
            model_name="playlistexporttarget",
            index=models.Index(
                fields=["sync_mode", "last_sync_status"],
                name="qt_export_target_auto_sync_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="playlistexporttarget",
            constraint=models.UniqueConstraint(
                fields=("account", "playlist", "destination_type"),
                name="queuetip_export_target_unique_per_dest",
            ),
        ),
        migrations.AddConstraint(
            model_name="playlistexporttarget",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("destination_type", "spotify"),
                        ("spotify_link__isnull", False),
                        ("subsonic_connection__isnull", True),
                    ),
                    models.Q(
                        ("destination_type", "subsonic"),
                        ("spotify_link__isnull", True),
                        ("subsonic_connection__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="queuetip_export_target_dest_fk_matches",
            ),
        ),
    ]
