# Generated by Django 5.2.10 on 2026-05-21 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("queuetip", "0009_export_targets_subsonic"),
    ]

    operations = [
        migrations.AddField(
            model_name="subsonicconnection",
            name="opensubsonic_extensions",
            field=models.JSONField(default=list),
        ),
    ]
