# Generated by Django 5.2.10 on 2026-05-21 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("queuetip", "0010_subsonic_opensubsonic_extensions"),
    ]

    operations = [
        migrations.AddField(
            model_name="subsonicconnection",
            name="auth_mode",
            field=models.CharField(
                choices=[
                    ("password", "Password"),
                    ("api_key", "API key (OpenSubsonic)"),
                ],
                default="password",
                max_length=16,
            ),
        ),
    ]
