# Generated by Django 5.2.10 on 2026-05-22 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("queuetip", "0011_subsonicconnection_auth_mode"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="playlistexporttarget",
            name="qt_export_target_auto_sync_idx",
        ),
        migrations.RemoveField(
            model_name="playlistexporttarget",
            name="sync_mode",
        ),
    ]
