# Generated by Django 5.2.10 on 2026-05-22 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("queuetip", "0012_drop_sync_mode"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exportsnapshottrack",
            name="snapshot",
        ),
        migrations.RemoveField(
            model_name="exportsnapshottrack",
            name="song",
        ),
        migrations.DeleteModel(
            name="ExportSnapshot",
        ),
        migrations.DeleteModel(
            name="ExportSnapshotTrack",
        ),
    ]
