# Generated by Django 5.2.10 on 2026-05-22 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("queuetip", "0013_drop_export_snapshots"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="magiclinkrequestlog",
            index=models.Index(
                fields=["identifier", "created_at"],
                name="queuetip_ma_identif_4d8bed_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="magiclinkrequestlog",
            index=models.Index(
                fields=["ip_address", "created_at"],
                name="queuetip_ma_ip_addr_542267_idx",
            ),
        ),
    ]
