# Generated by Django 5.2.10 on 2026-05-22 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("queuetip", "0014_magiclinkrequestlog_rate_limit_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="queuetipsignupallowlist",
            name="invited_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The Queuetip admin who invited this email. NULL for pre-existing entries or operator-CLI additions.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="queuetip.account",
            ),
        ),
    ]
