# Generated by Django 5.2.10 on 2026-05-22 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("queuetip", "0015_queuetipsignupallowlist_invited_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="last_signed_in_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Set whenever this account completes /auth/verify. NULL means the account was created (signup form submitted, AuthIdentity issued) but no magic link has ever been clicked.",
                null=True,
            ),
        ),
    ]
